### ISSUE TITLE
null

### ISSUE THREAD

**Issue by catshitz** [wdwind/JavMiniDriver#1]
null

**Comment by wdwind** [comment]
谢谢你的评论。
1. 能放一下具体截图吗？我自己用并没有不协调的感觉。
1. 这个有道理，我正在考虑怎么样加入页数信息。可能会在下个版本更新。
1. 视频截图确实有些小问题
    1. 首先我会微调一下css，如果页宽大于图片本身的宽度，则只放大到图片本身宽度。
    1. 关于图源，javscreens的最大问题是不全，很多番号都没有收录。会尝试一下能否把japanese-bukkake加入备用。
     1. pixhost暂时不在考虑范围内。原因是pixhost图片url没有固定结构，需要额外从其他网站搜索和解析，不符合小司机简单轻量的需求。

**Comment by catshitz** [comment]
https://bit.ly/32iLWXZ
1. 日期评分字体大小可否考虑缩至做题标题大小，去除“看过”（重要性较低，且子页已包含“想要”“看过”“拥有”），与番号一样的字体大小稍占用最重要的封面其次番号版面空间，影响直观注重点；另外颜色可考虑与老司机相同的红色，内容版面块字体主题红蓝，同时日期分数字体也不会因缩小而降低醒目程度。
2.japanese-bukkake因资源本身gokkun/fellatio(同好🤝)/bukkake偏多且大多非HD(1080p)而是720p，导致预览图本身比javscreens还小，优点在于偏老资源较全（特别前面几类），可作补充预览。

**Comment by catshitz** [comment]
> 1. 能放一下具体截图吗？我自己用并没有不协调的感觉。

https://bit.ly/32iLWXZ

日期评分字体大小可缩至标题大小，去除“看过”第二行（重要性低，且子页和侧栏已包含“想要”“看过”“拥有”），字体大小与番号相同会占用最重要的封面和番号标题空间，影响日文标题的直接观感，颜色可选与老司机相同的红色，内容栏目字体主题红蓝相间，以避免在红蓝中出现黑色略显突兀，同时日期评分字体不会因缩小而不起眼。

> 3\. 视频截图确实有些小问题

japanese-bukkake因资源本身gokkun+fellatio(同好🤝)/bukkake偏多且大多非FHD(1080p)而是720p，导致预览图本身比javscreens还小，优点在于稍老资源较全（特别前面几类），可作补充而非主预览。

**Comment by wdwind** [comment]
更新了一下。
1. 缩小了字体，把黑色改成了灰色（全红有点刺眼）。仍然保留了“几人看过”这一行，原因是这个和“评分”合起来才有参考价值。只看评分容易产生偏差。
2. 增加了页数信息，可以选择显示/隐藏。
3. 更改了截图放大逻辑，防止无限放大。同时增加了japanese-bukkake图源，但japanese-bukkake似乎图也不多。仍然在寻找其他合适的图源。

**Comment by catshitz** [comment]
谢谢！
> 2\. 增加了页数信息，可以选择显示/隐藏。
可以将“显示页数”记住吗？这样就不用每次打开新页或刷新页面再去点了。

**Comment by wdwind** [comment]
> 可以将“显示页数”记住吗？这样就不用每次打开新页或刷新页面再去点了。

更新了一下，是否显示页数会被保存在cookie里，这样就不用每次都点了。

另外我这里最后一页是显示正常的，如果你还有页码丢失的问题，可以把url发一下。

**Comment by catshitz** [comment]
> 如果你还有页码丢失的问题

早前出现过几次，目前暂无；

另外

1. 可否将所有子页页数直接默认设置为显示（包括分类子页和任一影片所有评论页面）？
因图书馆使用了Cloudflare防DDOS，加之有些网络采用动态IP，或浏览器开关和电脑重启等多种原因引起IP或cookie/UA等变动，造成网站cookie记录极短时间内失效（比如没一会儿就遇到的5秒CF DDOS刷新），最终导致即使是同一子页面，依赖cookie保存的显示页数状态，在短时间内又变回了隐藏状态，又得重新点击，造成很大不便，希望可以直接将页面默认设置为显示（如果可能，以优先级高于cookie的途径最佳），或直接使用网站原页数方案即可，无需隐藏。

2. 此外不仅是分类子页，任一影片页面最底端左侧的“阅读所有文章”链接选项目前也缺失，直接造成无法打开所有评论页面，并无法得知评论页数信息，希望能将其恢复。

**Comment by wdwind** [comment]
1. 我之前没想到会有cookie不稳定的情况。正在考虑用其他方法存储设置，比如存在local storage里。
1. 现在的页面加载确实有问题，刷新后就直接到第一页了（这应该是所有瀑布流共同的问题）。我打算更新一下，每次点“加载更多”的同时更新页面URL。
1. 评论和文章的“阅读所有xx”链接是故意取消掉的。有了“加载更多”之后，就没必要再跳到另一个页面里看评论和文章了。单独看影片页面是有意义的，但单独看评论/文章似乎完全没有意义，因为评论/文章的内容是不可预料的。暂时不打算对评论/文章做更多的更改。

**Comment by catshitz** [comment]
> 3\. 单独看评论/文章似乎完全没有意义，因为评论/文章的内容是不可预料的。

感谢回复。
单独看评论/文章是为了获取更清晰的预览图或更好的资源下载链接，以及其他各类与当前影片相关的有用信息，此外不少稍红影片页面评论区常常达数十页以上，不断点击向下加载会稍显麻烦；当然随着目前图书馆cn站大量涌入低质用户和垃圾广告，评论区的确充斥着大量的垃圾无用甚至令人反感的评论，网站管理不予重视也是事实；这点可做保留，留作观察。

**Comment by wdwind** [comment]
更新了一下
* “显示页数”的设置放到了local storage里
* 点击“加载更多”的同时会更新浏览器历史（包含URL）
