### ISSUE TITLE
视频预览源可以加上这个站点

### ISSUE THREAD

**Issue by jzysl123** [wdwind/JavMiniDriver#2]
http://dmm.xrbre.com/

**Comment by wdwind** [comment]
这个也是抓dmm的，没有必要加入。

**Comment by jzysl123** [comment]
> 这个也是抓dmm的，没有必要加入。

这个站点更新快 例如MIDE-714脚本现在抓不到  上面那个网站已经有了

**Comment by imjoeyli** [comment]
可以加入这个种子搜索源：https://idope.se

**Comment by wdwind** [comment]
> 可以加入这个种子搜索源：https://idope.se

可以，下个版本加上
