### ISSUE TITLE
能否增加排序功能？

### ISSUE THREAD

**Issue by YorkMoon** [wdwind/JavMiniDriver#5]
筛片的时候用老司机的评分排序，总觉得效率不高。
能否增加看过人数排序
谢谢！

**Comment by wdwind** [comment]
排序不太好做。数据是存在网站后端的，前端只能拿到当前页面的评分，所以只能对当前页面排序，但这就没什么用了。

**Comment by YorkMoon** [comment]
在当前页面用“加载更多”把所有页都加载出来，是否能够实现排序呢？

**Comment by wdwind** [comment]
可以，但这样太慢，而且有限流的风险

**Comment by YorkMoon** [comment]
明白了，谢谢。
还想问下，能否增加通过设定评分和人数条件来突出显示片子，类似这个脚本([Javdb评分筛选](https://sleazyfork.org/zh-CN/scripts/451530-javdb%E8%AF%84%E5%88%86%E7%AD%9B%E9%80%89))的功能

**Comment by wdwind** [comment]
这个可以，之后加一下

**Comment by YorkMoon** [comment]
谢谢，期待下次更新

**Comment by wdwind** [comment]
[#19a71a49b4bb900f2afe219a50c95fae150be567](https://github.com/wdwind/JavMiniDriver/commit/19a71a49b4bb900f2afe219a50c95fae150be567)
